// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FCFS() {
  return window['go']['main']['App']['FCFS']();
}

export function GeneratedProcesses() {
  return window['go']['main']['App']['GeneratedProcesses']();
}

export function RR() {
  return window['go']['main']['App']['RR']();
}

export function Regenerate() {
  return window['go']['main']['App']['Regenerate']();
}
