// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cmd} from '../models';

export function FCFS():Promise<string>;

export function GeneratedProcesses():Promise<string>;

export function GetState():Promise<Array<cmd.ProcessStateSnapshot>>;

export function RR():Promise<string>;

export function Regenerate():Promise<string>;
